// <auto-generated />
using System;
using BillBucket.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillBucket.Migrations
{
    [DbContext(typeof(BillBucketContext))]
    [Migration("20200116100057_M2")]
    partial class M2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BillBucket.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSiret")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("NumeroTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83147122-fc2b-4857-8087-abc84ec94b64"),
                            Adresse = "2 Rue du marathon",
                            Mail = "decathlon@decathlon.com",
                            Nom = "Decathlon",
                            NumeroSiret = "KFEFE4864FE8E7",
                            NumeroTelephone = "0650408090"
                        });
                });

            modelBuilder.Entity("BillBucket.Models.Facture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReglement")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<Guid>("IdClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroFacture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("Factures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3747b23b-d473-4b25-ab19-fc9125226816"),
                            DateEmission = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateReglement = new DateTime(2020, 1, 16, 11, 0, 56, 787, DateTimeKind.Local).AddTicks(8339),
                            Description = "Tapis de course",
                            IdClient = new Guid("83147122-fc2b-4857-8087-abc84ec94b64"),
                            NumeroFacture = 1
                        });
                });

            modelBuilder.Entity("BillBucket.Models.Prestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdFacture")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Montant")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdFacture");

                    b.ToTable("Prestations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("227cf6ce-9bc9-4d1b-8bdc-b97495b8bbd4"),
                            Description = "Nous dressons vos poules pour faire des oeufs carrés",
                            IdFacture = new Guid("3747b23b-d473-4b25-ab19-fc9125226816"),
                            Montant = 400.0,
                            Nom = "Dressage de poules"
                        },
                        new
                        {
                            Id = new Guid("f1eb2820-2c7a-4cea-8ee8-550dd30adbfb"),
                            Description = "Nous vous fournissons l'élite",
                            IdFacture = new Guid("3747b23b-d473-4b25-ab19-fc9125226816"),
                            Montant = 4000.0,
                            Nom = "Location de tueurs à gage"
                        });
                });

            modelBuilder.Entity("BillBucket.Models.Facture", b =>
                {
                    b.HasOne("BillBucket.Models.Client", "Client")
                        .WithMany("Factures")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BillBucket.Models.Prestation", b =>
                {
                    b.HasOne("BillBucket.Models.Facture", "Facture")
                        .WithMany("Prestations")
                        .HasForeignKey("IdFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
