//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrorConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavoirFaire
    {
        public System.Guid IdTerroriste { get; set; }
        public System.Guid IdCompetence { get; set; }
        public byte Niveau { get; set; }
    
        public virtual Competence Competence { get; set; }
        public virtual Terroriste Terroriste { get; set; }
    }
}
