//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrorConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TerrorDBEntities : DbContext
    {
        public TerrorDBEntities()
            : base("name=TerrorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competence> Competences { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<Terroriste> Terroristes { get; set; }
        public virtual DbSet<SavoirFaire> SavoirFaires { get; set; }
    }
}
