//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrorConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terroriste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terroriste()
        {
            this.Filleuls = new HashSet<Terroriste>();
            this.SavoirFaires = new HashSet<SavoirFaire>();
        }
    
        public System.Guid Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Alias { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.Guid> IdParrain { get; set; }
        public Nullable<System.Guid> IdOrganisation { get; set; }
        public Nullable<decimal> MiseAPrix { get; set; }
        public int NombreDeVictimes { get; set; }
        public Nullable<double> Taille { get; set; }
        public Nullable<bool> EstMort { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terroriste> Filleuls { get; set; }
        public virtual Terroriste Parrain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavoirFaire> SavoirFaires { get; set; }
    }
}
