//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickContact.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid Id { get; set; }
        public string Nom { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.Guid> IdCategorie { get; set; }
    
        public virtual Categorie Categorie { get; set; }
    }
}
