// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scolarite.Models;

namespace Scolarite.Migrations
{
    [DbContext(typeof(EcoleContext))]
    [Migration("20200115154220_M2")]
    partial class M2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Scolarite.Models.Eleve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Remarque")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eleves");

                    b.HasData(
                        new
                        {
                            Id = new Guid("652c7fe5-1b08-478e-9fb3-3adaaec2e8bc"),
                            DateNaissance = new DateTime(2000, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Mauras",
                            Prenom = "Milka"
                        },
                        new
                        {
                            Id = new Guid("cc3cbdec-7907-4c99-8003-12f108256206"),
                            DateNaissance = new DateTime(2002, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Mauras",
                            Prenom = "Olympe"
                        });
                });

            modelBuilder.Entity("Scolarite.Models.Evaluation", b =>
                {
                    b.Property<Guid>("IdEleve")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMatiere")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Appreciation")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.HasKey("IdEleve", "IdMatiere", "Date");

                    b.HasIndex("IdMatiere");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("Scolarite.Models.Matiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Matieres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b018172-0593-4f52-ab0c-760ad24c4eb4"),
                            Nom = "Mathématiques"
                        },
                        new
                        {
                            Id = new Guid("1c54e7eb-f728-47c2-98b6-2593d6465ef6"),
                            Nom = "Français"
                        });
                });

            modelBuilder.Entity("Scolarite.Models.Evaluation", b =>
                {
                    b.HasOne("Scolarite.Models.Eleve", "Eleve")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdEleve")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scolarite.Models.Matiere", "Matiere")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
